/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lutysoft.scabs.view.formulario;

import com.lutysoft.scabs.controller.CadastroFaccaoController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author lutye
 */
public class CadastroFaccao extends javax.swing.JFrame {
    
    private CadastroFaccaoController cadastroFaccaoController;
    
    /**
     * Creates new form CadastroFaccao
     */
    public CadastroFaccao() {
        initComponents();
        setLocationRelativeTo(null);
        this.cadastroFaccaoController = new CadastroFaccaoController(this);
        eventos();
    }
    
    private void eventos(){
        botaoCadastroFaccaoSalvar.addActionListener(cadastroFaccaoController);
        botaoCadastroFaccaoCancelar.addActionListener(cadastroFaccaoController);
        botaoCadastroFaccaoConsultar.addActionListener(cadastroFaccaoController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCadastroFaccaoFaccao = new javax.swing.JLabel();
        labelCadastroFaccaoMensagem = new javax.swing.JLabel();
        txtCadastroFaccaoFaccao = new javax.swing.JTextField();
        botaoCadastroFaccaoSalvar = new javax.swing.JButton();
        botaoCadastroFaccaoConsultar = new javax.swing.JButton();
        botaoCadastroFaccaoCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.SystemColor.control);
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 275));

        labelCadastroFaccaoFaccao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelCadastroFaccaoFaccao.setText("Facção:");

        labelCadastroFaccaoMensagem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        labelCadastroFaccaoMensagem.setForeground(new java.awt.Color(255, 51, 51));
        labelCadastroFaccaoMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCadastroFaccaoFaccao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCadastroFaccaoFaccao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        botaoCadastroFaccaoSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoSalvar.setText("Salvar");
        botaoCadastroFaccaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroFaccaoSalvarActionPerformed(evt);
            }
        });

        botaoCadastroFaccaoConsultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoConsultar.setText("Consultar");
        botaoCadastroFaccaoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroFaccaoConsultarActionPerformed(evt);
            }
        });

        botaoCadastroFaccaoCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastroFaccaoCancelar)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelCadastroFaccaoFaccao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCadastroFaccaoFaccao)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 111, Short.MAX_VALUE)
                        .addComponent(botaoCadastroFaccaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastroFaccaoConsultar)))
                .addContainerGap(61, Short.MAX_VALUE))
            .addComponent(labelCadastroFaccaoMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelCadastroFaccaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroFaccaoFaccao, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(labelCadastroFaccaoFaccao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCadastroFaccaoSalvar)
                    .addComponent(botaoCadastroFaccaoConsultar))
                .addGap(39, 39, 39)
                .addComponent(botaoCadastroFaccaoCancelar)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroFaccaoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroFaccaoConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroFaccaoConsultarActionPerformed

    private void botaoCadastroFaccaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroFaccaoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroFaccaoSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFaccao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastroFaccaoCancelar;
    private javax.swing.JButton botaoCadastroFaccaoConsultar;
    private javax.swing.JButton botaoCadastroFaccaoSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCadastroFaccaoFaccao;
    private javax.swing.JLabel labelCadastroFaccaoMensagem;
    private javax.swing.JTextField txtCadastroFaccaoFaccao;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCadastroFaccaoFaccao(){
        return txtCadastroFaccaoFaccao;
    }
    
    public JButton getBotaoCadastroFaccaoSalvar(){
        return botaoCadastroFaccaoSalvar;
    }
    
    public JButton getBotaoCadastroFaccaoConsultar(){
        return botaoCadastroFaccaoConsultar;
    }
    
    public JButton getBotaoCadastroFaccaoCancelar(){
        return botaoCadastroFaccaoCancelar;
    }
    
    public JLabel getLabelCadastroFaccaoMensagem(){
        return labelCadastroFaccaoMensagem;
    }

}
