/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lutysoft.scabs.view.formulario;

import com.lutysoft.scabs.controller.CadastroFaccaoController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author lutye
 */
public class CadastroFaccao extends javax.swing.JFrame {
    
    private CadastroFaccaoController cadastroFaccaoController;
    
    /**
     * Creates new form CadastroFaccao
     */
    public CadastroFaccao() {
        initComponents();
        setLocationRelativeTo(null);
        this.cadastroFaccaoController = new CadastroFaccaoController(this);
        eventos();
    }
    
    private void eventos(){
        botaoCadastroFaccaoSalvar.addActionListener(cadastroFaccaoController);
        botaoCadastroFaccaoVoltar.addActionListener(cadastroFaccaoController);
        botaoCadastroFaccaoEditar.addActionListener(cadastroFaccaoController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCadastroFaccaoFaccao = new javax.swing.JLabel();
        labelCadastroFaccaoMensagem = new javax.swing.JLabel();
        txtCadastroFaccaoFaccao = new javax.swing.JTextField();
        botaoCadastroFaccaoSalvar = new javax.swing.JButton();
        botaoCadastroFaccaoVoltar = new javax.swing.JButton();
        botaoCadastroFaccaoEditar = new javax.swing.JButton();
        labelCadastroFaccaoId = new javax.swing.JLabel();
        txtCadastroFaccaoId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(java.awt.SystemColor.control);
        jPanel1.setPreferredSize(new java.awt.Dimension(558, 275));

        labelCadastroFaccaoFaccao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelCadastroFaccaoFaccao.setText("Facção:");

        labelCadastroFaccaoMensagem.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        labelCadastroFaccaoMensagem.setForeground(new java.awt.Color(255, 51, 51));
        labelCadastroFaccaoMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        txtCadastroFaccaoFaccao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCadastroFaccaoFaccao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        botaoCadastroFaccaoSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoSalvar.setText("Salvar");
        botaoCadastroFaccaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroFaccaoSalvarActionPerformed(evt);
            }
        });

        botaoCadastroFaccaoVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoVoltar.setText("Voltar");
        botaoCadastroFaccaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroFaccaoVoltarActionPerformed(evt);
            }
        });

        botaoCadastroFaccaoEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        botaoCadastroFaccaoEditar.setText("Editar");

        labelCadastroFaccaoId.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelCadastroFaccaoId.setText("ID:");

        txtCadastroFaccaoId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtCadastroFaccaoId.setText("0");
        txtCadastroFaccaoId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtCadastroFaccaoId.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCadastroFaccaoMensagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastroFaccaoVoltar)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botaoCadastroFaccaoSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastroFaccaoEditar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelCadastroFaccaoId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCadastroFaccaoId, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(labelCadastroFaccaoFaccao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCadastroFaccaoFaccao, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(labelCadastroFaccaoMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroFaccaoId, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(labelCadastroFaccaoId))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroFaccaoFaccao, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(labelCadastroFaccaoFaccao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastroFaccaoEditar)
                    .addComponent(botaoCadastroFaccaoSalvar))
                .addGap(40, 40, 40)
                .addComponent(botaoCadastroFaccaoVoltar)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroFaccaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroFaccaoSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroFaccaoSalvarActionPerformed

    private void botaoCadastroFaccaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroFaccaoVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastroFaccaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFaccao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFaccao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastroFaccaoEditar;
    private javax.swing.JButton botaoCadastroFaccaoSalvar;
    private javax.swing.JButton botaoCadastroFaccaoVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCadastroFaccaoFaccao;
    private javax.swing.JLabel labelCadastroFaccaoId;
    private javax.swing.JLabel labelCadastroFaccaoMensagem;
    private javax.swing.JTextField txtCadastroFaccaoFaccao;
    private javax.swing.JTextField txtCadastroFaccaoId;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCadastroFaccaoFaccao(){
        return txtCadastroFaccaoFaccao;
    }
    
    public JTextField getTxtCadastroFaccaoId(){
        return txtCadastroFaccaoId;
    }
    
    public JButton getBotaoCadastroFaccaoSalvar(){
        return botaoCadastroFaccaoSalvar;
    }
    
    public JButton getBotaoCadastroFaccaoEditar(){
        return botaoCadastroFaccaoEditar;
    }
    
    public JButton getBotaoCadastroFaccaoCancelar(){
        return botaoCadastroFaccaoVoltar;
    }
    
    public JLabel getLabelCadastroFaccaoMensagem(){
        return labelCadastroFaccaoMensagem;
    }

}
